vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<leader>q", ":q<cr>")
vim.keymap.set("n", "<leader>r", ":update<cr> :source<cr>")
vim.keymap.set("n", "<A-(>", ":bp<cr>")
vim.keymap.set("n", "<A-)>", ":bn<cr>")
vim.keymap.set("n", "<A-d>", ":bd<cr>")
vim.keymap.set("n", "<A-D>", ":bd!<cr>")
vim.keymap.set("n", "<leader>p", ":lua =vim.pack.get()<cr>", { desc = "print all installed plugins" })
